#!/usr/bin/env python3
"""Run the bounded piston/liner thermal-state RC campaign.

The default gas history is generated by the existing thermodynamic proxy in
``microengine_rig.py`` (sparked, non-Cantera heat release, existing 600
W/m2-K wall coefficient).  Supplying ``--history`` lets a later measured or
CFD-derived p(theta), T(theta) history replace that proxy without changing the
RC solver.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from microengine_rig import RigConfig, simulate
from physics.thermal_clearance import ThermalStrainProfile, annulus_leakage_from_clearance
from physics.thermal_state import (
    ConductiveLink,
    HistoryPoint,
    ThermalNode,
    ThermalRCConfig,
    default_links,
    default_nodes,
    load_history_csv,
    run_thermal_rc,
)

MATERIALS_PATH = ROOT / "data" / "materials" / "thermal_properties.json"
DEFAULT_OUTPUT = ROOT / "data" / "thermal"
DEFAULT_HISTORY = DEFAULT_OUTPUT / "engine_history_proxy.csv"


def load_materials() -> tuple[dict[str, Any], dict[str, ThermalStrainProfile]]:
    payload = json.loads(MATERIALS_PATH.read_text(encoding="utf-8"))
    materials = {item["id"]: item for item in payload["materials"]}
    profiles = {key: ThermalStrainProfile(tuple(tuple(point) for point in item["strain_points"])) for key, item in materials.items()}
    return materials, profiles


def write_engine_history(path: Path) -> None:
    """Generate a portable history using the existing nonreacting proxy path."""
    config = RigConfig(
        bore_mm=8.5,
        stroke_mm=7.0,
        compression_ratio=7.75,
        rod_stroke_ratio=1.6,
        rpm=1200.0,
        intake_pressure_bar=3.0,
        intake_temperature_K=300.0,
        equivalence_ratio=0.4,
        ignition_mode="spark",
        spark_deg_atdc=-10.0,
        burn_duration_deg=35.0,
        target_burn_fraction=0.35,
        wall_mode="finite",
        wall_temperature_K=560.0,
        effective_h_W_m2K=600.0,
        wall_mass_g=2.0,
        wall_cp_J_kgK=850.0,
        step_deg=1.0,
    )
    rows, summary = simulate(config)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=("deg", "P_bar", "T_K", "pistonVelocity_m_s"))
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row[field] for field in writer.fieldnames})
    path.with_suffix(".metadata.json").write_text(json.dumps({
        "source": "microengine_rig.py simulate",
        "classification": "calculated proxy history, not measured or CFD heat flux",
        "effective_h_W_m2K": config.effective_h_W_m2K,
        "wall_mass_g": config.wall_mass_g,
        "wall_cp_J_kgK": config.wall_cp_J_kgK,
        "max_temperature_K": max(row["T_K"] for row in rows),
        "max_pressure_bar": max(row["P_bar"] for row in rows),
        "proxy_summary": {key: value for key, value in summary.items() if isinstance(value, (str, int, float, bool, type(None)))},
    }, indent=2) + "\n", encoding="utf-8")


def air_viscosity_sutherland(temperature_K: float) -> float:
    return 1.716e-5 * (temperature_K / 273.15) ** 1.5 * (273.15 + 110.4) / (temperature_K + 110.4)


def scaled_nodes(scale: float, initial_temperature_K: float, config: ThermalRCConfig) -> tuple[ThermalNode, ...]:
    nodes = []
    for node in default_nodes(config):
        nodes.append(ThermalNode(
            node.name,
            node.mass_kg,
            node.cp_J_kgK,
            initial_temperature_K,
            node.external_temperature_K,
            node.external_conductance_W_K * scale,
        ))
    return tuple(nodes)


def scaled_history(history: list[HistoryPoint], temperature_offset_K: float) -> list[HistoryPoint]:
    return [HistoryPoint(p.deg, p.pressure_bar, p.gas_temperature_K + temperature_offset_K, p.piston_velocity_m_s, p.dt_s) for p in history]


def percentile(values: list[float], fraction: float) -> float:
    ordered = sorted(values)
    if not ordered:
        return float("nan")
    position = fraction * (len(ordered) - 1)
    low = math.floor(position)
    high = math.ceil(position)
    if low == high:
        return ordered[low]
    return ordered[low] + (ordered[high] - ordered[low]) * (position - low)


def enrich_rows(result: dict[str, Any], config: ThermalRCConfig) -> list[dict[str, Any]]:
    rows = []
    for row in result["history_rows"]:
        row = dict(row)
        # Use the minimum paired radial gap for the conservative leakage
        # screen; retain the individual pair columns for diagnosis.
        hot_clearance = row["hot_clearance_min_path_3p0_um"]
        leakage = annulus_leakage_from_clearance(
            hot_clearance,
            pressure_up_bar=row["pressure_bar"],
            pressure_down_bar=1.0,
            temperature_K=row["gas_temperature_K"],
            viscosity_Pa_s=air_viscosity_sutherland(row["gas_temperature_K"]),
            bore_diameter_mm=config.bore_mm,
            skirt_length_mm=8.0,
            eccentricity=0.0,
        )
        row["annulus_mdot_mg_s_for_3um_cold"] = (
            None if leakage["mass_flow_kg_s"] is None else float(leakage["mass_flow_kg_s"]) * 1e6
        )
        row["annulus_clearance_path_for_3um_cold"] = "minimum_of_crown_liner_tdc_skirt_liner_tdc_skirt_liner_lower"
        rows.append(row)
    return rows


def run_case(
    history: list[HistoryPoint],
    materials: dict[str, Any],
    profiles: dict[str, ThermalStrainProfile],
    piston_material: str,
    liner_material: str,
    h_model: str,
    *,
    h_scale: float = 1.0,
    cooling_scale: float = 1.0,
    temperature_offset_K: float = 0.0,
    initial_temperature_K: float = 300.0,
) -> dict[str, Any]:
    config = ThermalRCConfig(
        piston_material=piston_material,
        liner_material=liner_material,
        h_model=h_model,
        h_ref_W_m2K=600.0 * h_scale,
        piston_conductivity_W_mK=float(materials[piston_material]["thermal_conductivity_W_mK"]),
        liner_conductivity_W_mK=float(materials[liner_material]["thermal_conductivity_W_mK"]),
        max_warmup_cycles=120,
        min_warmup_cycles=10,
    )
    result = run_thermal_rc(
        scaled_history(history, temperature_offset_K),
        config,
        piston_cte=profiles[piston_material],
        liner_cte=profiles[liner_material],
        nodes=scaled_nodes(cooling_scale, initial_temperature_K, config),
    )
    result["case"] = {
        "piston_material": piston_material,
        "liner_material": liner_material,
        "h_model": h_model,
        "h_scale": h_scale,
        "cooling_scale": cooling_scale,
        "temperature_offset_K": temperature_offset_K,
        "initial_temperature_K": initial_temperature_K,
    }
    result["history_rows"] = enrich_rows(result, config)
    lower = result["required_cold_clearance_for_hot_2_to_5_um"]["lower_bound_um"]
    if lower > 0:
        cold = annulus_leakage_from_clearance(
            lower,
            pressure_up_bar=6.5,
            pressure_down_bar=1.0,
            temperature_K=300.0,
            viscosity_Pa_s=air_viscosity_sutherland(300.0),
            bore_diameter_mm=config.bore_mm,
            skirt_length_mm=8.0,
            eccentricity=0.0,
        )
        result["cold_static_mdot_mg_s_at_lower_bound"] = float(cold["mass_flow_kg_s"]) * 1e6 if cold["mass_flow_kg_s"] is not None else None
    else:
        result["cold_static_mdot_mg_s_at_lower_bound"] = None
    return result


def compact_case(result: dict[str, Any]) -> dict[str, Any]:
    bounds = result["required_cold_clearance_for_hot_2_to_5_um"]
    return {
        "case": result["case"],
        "converged": result["converged"],
        "periodic_converged": result["periodic_converged"],
        "warmup_converged": result["warmup_converged"],
        "cycles_completed": result["cycles_completed"],
        "periodic_info": result["periodic_info"],
        "startup_clearance_3um": result["startup_clearance_3um"],
        "warmup_min_path_hot_clearance_3um": result["warmup_min_path_hot_clearance_3um"],
        "warmup_max_path_hot_clearance_3um": result["warmup_max_path_hot_clearance_3um"],
        "periodic_min_path_hot_clearance_3um": result["periodic_min_path_hot_clearance_3um"],
        "periodic_max_path_hot_clearance_3um": result["periodic_max_path_hot_clearance_3um"],
        "piston_crown_min_K": result["piston_crown_min_K"],
        "piston_crown_max_K": result["piston_crown_max_K"],
        "piston_skirt_min_K": result["piston_skirt_min_K"],
        "piston_skirt_max_K": result["piston_skirt_max_K"],
        "liner_tdc_min_K": result["liner_tdc_min_K"],
        "liner_tdc_max_K": result["liner_tdc_max_K"],
        "liner_lower_min_K": result["liner_lower_min_K"],
        "liner_lower_max_K": result["liner_lower_max_K"],
        "required_cold_clearance_for_hot_2_to_5_um": bounds,
        "cold_static_mdot_mg_s_at_lower_bound": result["cold_static_mdot_mg_s_at_lower_bound"],
        "final_node_temperatures_K": result["final_node_temperatures_K"],
        "model_classification": result["model_classification"],
    }


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = sorted({key for row in rows for key in row})
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def write_plots(out: Path, primary_results: dict[str, dict[str, Any]], uncertainty: list[dict[str, Any]]) -> list[str]:
    """Write compact, decision-oriented plots when Matplotlib is available."""
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        return []
    figure_dir = out / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    constant = primary_results["constant_h"]
    rows = constant["history_rows"]
    cycles = constant["cycle_rows"]
    fig, ax = plt.subplots(figsize=(6.4, 4.0))
    ax.plot([r["cycle"] for r in cycles], [r["piston_skirt_end_K"] for r in cycles], label="piston skirt")
    ax.plot([r["cycle"] for r in cycles], [r["liner_tdc_end_K"] for r in cycles], label="liner TDC band")
    ax.plot([r["cycle"] for r in cycles], [r["max_temperature_K"] for r in cycles], label="network maximum", linestyle="--")
    ax.set(xlabel="modeled 100 ms cycle", ylabel="temperature (K)", title="RC warm-up: Al 4032 / 4140, constant h")
    ax.legend()
    fig.tight_layout()
    path = figure_dir / "thermal_state_cycle_warmup.png"
    fig.savefig(path, dpi=160)
    plt.close(fig)
    written.append(path.relative_to(out).as_posix())

    fig, ax = plt.subplots(figsize=(6.4, 4.0))
    for h_model, result in primary_results.items():
        r = result["history_rows"]
        ax.plot([x["deg"] for x in r], [x["hot_clearance_min_path_3p0_um"] for x in r], label=h_model)
    ax.axhline(0.0, color="black", linewidth=0.8)
    ax.axhspan(2.0, 5.0, color="tab:green", alpha=0.12, label="2–5 µm hot window")
    ax.set(xlabel="crank angle (deg, modeled pass)", ylabel="minimum paired hot clearance for 3 µm cold (µm)", title="Thermal-fit trajectory")
    ax.legend(fontsize=8)
    fig.tight_layout()
    path = figure_dir / "thermal_state_hot_clearance_trajectory.png"
    fig.savefig(path, dpi=160)
    plt.close(fig)
    written.append(path.relative_to(out).as_posix())

    fig, ax = plt.subplots(figsize=(6.4, 4.0))
    for h_model in ("constant_h", "angle_correlation"):
        selected = [row for row in uncertainty if row["h_model"] == h_model]
        ax.scatter([row["required_cold_lower_um"] for row in selected], [row["required_cold_upper_um"] for row in selected], s=16, alpha=0.65, label=h_model)
    ax.axvline(0.0, color="black", linewidth=0.8)
    ax.axhline(0.0, color="black", linewidth=0.8)
    ax.set(xlabel="cold fit lower bound for ≥2 µm hot (µm)", ylabel="cold fit upper bound for ≤5 µm hot (µm)", title="Bounded thermal sensitivity cases")
    ax.legend(fontsize=8)
    fig.tight_layout()
    path = figure_dir / "thermal_state_fit_sensitivity.png"
    fig.savefig(path, dpi=160)
    plt.close(fig)
    written.append(path.relative_to(out).as_posix())
    return written


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--history", type=Path, default=DEFAULT_HISTORY)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--plots", action="store_true", help="write decision plots (requires matplotlib)")
    args = parser.parse_args()
    if not args.history.exists() or args.history.resolve() == DEFAULT_HISTORY.resolve():
        write_engine_history(args.history)
    history = load_history_csv(args.history)
    materials, profiles = load_materials()
    pairs = json.loads(MATERIALS_PATH.read_text(encoding="utf-8"))["screened_pairs"]
    base_cases = []
    primary_results: dict[str, dict[str, Any]] = {}
    history_rows = []
    warmup_rows = []
    for piston_material, liner_material in pairs:
        for h_model in ("constant_h", "angle_correlation"):
            result = run_case(history, materials, profiles, piston_material, liner_material, h_model)
            base_cases.append(compact_case(result))
            if piston_material == "al_4032_t6" and liner_material == "steel_4140":
                primary_results[h_model] = result
                for row in result["history_rows"]:
                    history_rows.append({"piston_material": piston_material, "liner_material": liner_material, "h_model": h_model, **row})
                for row in result["cycle_rows"]:
                    warmup_rows.append({"piston_material": piston_material, "liner_material": liner_material, "h_model": h_model, **row})

    # Bounded uncertainty envelope around the primary Al/steel case.  These
    # are sensitivity assumptions, not measured probabilities.
    uncertainty = []
    lower_values, upper_values = [], []
    for h_model in ("constant_h", "angle_correlation"):
        for h_scale in (0.75, 1.0, 1.25):
            for cooling_scale in (0.5, 1.0, 1.5):
                for temperature_offset_K in (-20.0, 0.0, 20.0):
                    result = run_case(
                        history, materials, profiles, "al_4032_t6", "steel_4140", h_model,
                        h_scale=h_scale,
                        cooling_scale=cooling_scale,
                        temperature_offset_K=temperature_offset_K,
                        initial_temperature_K=300.0,
                    )
                    bounds = result["required_cold_clearance_for_hot_2_to_5_um"]
                    lower_values.append(bounds["lower_bound_um"])
                    upper_values.append(bounds["upper_bound_um"])
                    uncertainty.append({
                        **result["case"],
                        "converged": result["converged"],
                        "periodic_converged": result["periodic_converged"],
                        "warmup_converged": result["warmup_converged"],
                        "cycles_completed": result["cycles_completed"],
                        "piston_skirt_min_K": result["piston_skirt_min_K"],
                        "piston_skirt_max_K": result["piston_skirt_max_K"],
                        "liner_tdc_min_K": result["liner_tdc_min_K"],
                        "liner_tdc_max_K": result["liner_tdc_max_K"],
                        "required_cold_lower_um": bounds["lower_bound_um"],
                        "required_cold_upper_um": bounds["upper_bound_um"],
                        "feasible": bounds["feasible"],
                        "nonnegative_cold_fit_feasible": bounds["nonnegative_cold_fit_feasible"],
                        "lower_bound_is_negative_interference_target": bounds["lower_bound_is_negative_interference_target"],
                        "warmup_min_path_hot_clearance_3um": result["warmup_min_path_hot_clearance_3um"],
                        "periodic_min_path_hot_clearance_3um": result["periodic_min_path_hot_clearance_3um"],
                        "assumption_label": "engineering sensitivity grid; not measured production statistics",
                    })

    out = args.output_dir.resolve()
    out.mkdir(parents=True, exist_ok=True)
    history_path = args.history.resolve()
    try:
        history_label = history_path.relative_to(ROOT).as_posix()
    except ValueError:
        history_label = history_path.name
    history_classification = "calculated proxy from microengine_rig.py; replace with measured/CFD history when available" if history_path == DEFAULT_HISTORY.resolve() else "custom supplied history; caller must provide provenance and classification"
    write_csv(out / "thermal_state_history.csv", history_rows)
    write_csv(out / "thermal_state_warmup.csv", warmup_rows)
    write_csv(out / "thermal_state_uncertainty.csv", uncertainty)
    summary = {
        "campaign": "thermal state -> hot clearance -> annulus leakage",
        "status": "screening_only",
        "history_file": history_label,
        "history_sha256": hashlib.sha256(history_path.read_bytes()).hexdigest(),
        "history_classification": history_classification,
        "warmup_file": "data/thermal/thermal_state_warmup.csv",
        "rpm": 1200.0,
        "modeled_history_span_deg": [history[0].deg, history[-1].deg],
        "four_stroke_period_ms": 100.0,
        "modeled_pass_ms": sum(point.dt_s for point in history) * 1000.0,
        "idle_duration_ms": 50.0,
        "ambient_temperature_K": ThermalRCConfig().ambient_temperature_K,
        "block_ambient_conductance_W_K": ThermalRCConfig().block_ambient_conductance_W_K,
        "max_warmup_cycles": 120,
        "periodic_fixed_point": True,
        "periodic_method": "dense Gaussian-elimination solve of one-cycle T_end=A*T_start+b",
        "warmup_convergence_tolerance_K": ThermalRCConfig().convergence_tolerance_K,
        "warmup_convergence_note": "finite cold-to-warm trajectory is reported separately; max cycle count is not treated as convergence",
        "nodes": ["piston_crown", "piston_skirt", "rod_crank", "liner_tdc", "liner_lower", "head_deck", "block"],
        "closures": {
            "constant_h": "existing repository closure, h=600 W/m2-K",
            "angle_correlation": "Woschni-shaped pressure/temperature/piston-speed sensitivity; assumed, not validated",
        },
        "material_pairs": pairs,
        "node_capacities_J_K": {node.name: node.capacity_J_K for node in scaled_nodes(1.0, 300.0, ThermalRCConfig())},
        "conductive_links_W_K_reference": [{"node_a": link.node_a, "node_b": link.node_b, "conductance_W_K": link.conductance_W_K} for link in default_links(ThermalRCConfig())],
        "conductivity_scaling": "piston and liner links scale linearly with selected k relative to the Al-4032/4140 reference pair; link geometry remains an engineering bracket",
        "gas_area_assignment": "crown/head and liner TDC/lower bands receive direct chamber-side convection; conventional piston skirt receives zero direct gas area and heats through solid paths",
        "base_case_count": len(base_cases),
        "uncertainty_case_count": len(uncertainty),
        "base_cases": base_cases,
        "uncertainty_envelope": {
            "required_cold_lower_p05_um": percentile(lower_values, 0.05),
            "required_cold_lower_p95_um": percentile(lower_values, 0.95),
            "required_cold_upper_p05_um": percentile(upper_values, 0.05),
            "required_cold_upper_p95_um": percentile(upper_values, 0.95),
            "engineering_assumption_label": "95% percentile envelope of bounded sensitivity cases, not a confidence interval",
        },
        "uncertainty_gate_counts": {
            "periodic_fixed_point_solved": sum(bool(row["periodic_converged"]) for row in uncertainty),
            "nonnegative_cold_fit_feasible": sum(bool(row["nonnegative_cold_fit_feasible"]) for row in uncertainty),
            "total": len(uncertainty),
        },
        "model_classification": {
            "measured": "none",
            "literature_derived": "material CTE/conductivity inputs in data/materials",
            "calculated": "RC node temperatures, inverse hot-fit bounds and annulus sensitivity",
            "assumed": "node masses/cp, conductances, area partition, h sensitivity and proxy history",
            "extrapolated": "four-stroke idle segment and thermal steady state from repeated cycles",
        },
    }
    summary["plots"] = write_plots(out, primary_results, uncertainty) if args.plots else []
    (out / "thermal_state_summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"output_dir": str(out), "base_cases": len(base_cases), "uncertainty_cases": len(uncertainty), "summary": str(out / "thermal_state_summary.json")}, indent=2))


if __name__ == "__main__":
    main()
