#!/usr/bin/env python3
"""Create and run the CFD-01 OpenFOAM 14 mesh-convergence cases.

Run this from a WSL shell after sourcing /opt/openfoam14/etc/bashrc.  The
script deliberately leaves a failed case and its logs in place so that it can
be reported as a failed row rather than silently omitted.
"""
from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path
import re
import shutil
import subprocess
import time


ROOT = Path(__file__).resolve().parents[1]
BORE_M = 0.0085
STROKE_M = 0.007
CR = 7.75
WEDGE_DEG = 5.0
LEVELS = {
    "coarse": {"radial": 22, "azimuthal": 3, "axial": 41, "nominal_mm": 0.20},
    "medium": {"radial": 43, "azimuthal": 3, "axial": 41, "nominal_mm": 0.10},
    "fine": {"radial": 85, "azimuthal": 3, "axial": 41, "nominal_mm": 0.05},
}


def clearance_height() -> float:
    return STROKE_M / (CR - 1.0)


def block_mesh_dict(radial: int, azimuthal: int, axial: int) -> str:
    """One-cell 5-degree symmetry sector, initially positioned at BDC.

    A 50-micrometre axis-core regularisation avoids the singular wedge cell at
    r=0. The 5-degree sector uses planar chord faces rather than curved block
    edges so strict checkMesh quality metrics remain meaningful; the combined
    chord and core-volume difference is below the 0.2% volume criterion.
    """
    radius = BORE_M / 2.0
    inner_radius = 0.00005
    height = clearance_height() + STROKE_M
    half_angle = math.radians(WEDGE_DEG / 2.0)
    x, y = radius * math.cos(half_angle), radius * math.sin(half_angle)
    return f'''/* Generated by scripts/run_cfd01.py; do not hand-edit. */
FoamFile
{{
    format ascii;
    class dictionary;
    location "system";
    object blockMeshDict;
}}

vertices
(
    ({inner_radius * math.cos(half_angle):.12g} {-inner_radius * math.sin(half_angle):.12g} {height:.12g})
    ({x:.12g} {-y:.12g} {height:.12g})
    ({x:.12g} {y:.12g} {height:.12g})
    ({inner_radius * math.cos(half_angle):.12g} {inner_radius * math.sin(half_angle):.12g} {height:.12g})
    ({inner_radius * math.cos(half_angle):.12g} {-inner_radius * math.sin(half_angle):.12g} 0)
    ({x:.12g} {-y:.12g} 0)
    ({x:.12g} {y:.12g} 0)
    ({inner_radius * math.cos(half_angle):.12g} {inner_radius * math.sin(half_angle):.12g} 0)
);

blocks
(
    // Start at the fixed head so the radial, azimuthal, axial ordering is right-handed.
    hex (4 5 6 7 0 1 2 3) ({radial} {azimuthal} {axial}) simpleGrading (1 1 1)
);

boundary
(
    piston
    {{
        type wall;
        // The crank mover translates in +axis.  At -180 CAD the piston is
        // therefore the lower z-face and travels upward toward the head.
        faces ((4 5 6 7));
    }}
    liner
    {{
        type wall;
        faces ((1 2 6 5));
    }}
    cylinderHead
    {{
        type wall;
        faces ((0 3 2 1));
    }}
    axisCore
    {{
        type symmetry;
        faces ((0 4 7 3));
    }}
    symmetryMinus
    {{
        type symmetryPlane;
        faces ((0 1 5 4));
    }}
    symmetryPlus
    {{
        type symmetryPlane;
        faces ((3 7 6 2));
    }}
);
'''


def run(command: list[str], case: Path, log_name: str) -> None:
    log_path = case / log_name
    with log_path.open("w") as log:
        result = subprocess.run(command, cwd=case, stdout=log, stderr=subprocess.STDOUT)
    if result.returncode:
        raise RuntimeError(f"{' '.join(command)} failed; see {log_path}")


def initialise_tracer(case: Path) -> None:
    """Write the 20%-volume shell tracer field from the actual mesh centres."""
    run(
        ["postProcess", "-func", "writeCellCentres", "-time", "-180"],
        case,
        "log.initialCellCentres",
    )
    centre_text = (case / "-180" / "C").read_text()
    match = re.search(
        r"internalField\s+nonuniform\s+List<vector>\s+\d+\s*\(\s*(.*?)\s*\)\s*;",
        centre_text,
        flags=re.S,
    )
    if not match:
        raise RuntimeError("could not parse OpenFOAM cell-centre field")
    core_radius = (BORE_M / 2.0) * math.sqrt(0.8)
    tracer_values = []
    for line in match.group(1).splitlines():
        line = line.strip()
        if not line:
            continue
        x, y, _ = (float(value) for value in line.strip("()").split())
        tracer_values.append(0.0 if math.hypot(x, y) <= core_radius else 1.0)
    if not tracer_values or not any(tracer_values) or all(tracer_values):
        raise RuntimeError("shell/core tracer selection is empty or uniform")
    entries = "\n".join(f"{value:.1f}" for value in tracer_values)
    (case / "-180" / "tracer").write_text(f'''FoamFile
{{
    format ascii;
    class volScalarField;
    location "-180";
    object tracer;
}}

dimensions [0 0 0 0 0 0 0];
internalField nonuniform List<scalar>
{len(tracer_values)}
(
{entries}
);
boundaryField
{{
    piston {{ type zeroGradient; }}
    liner {{ type zeroGradient; }}
    cylinderHead {{ type zeroGradient; }}
    axisCore {{ type zeroGradient; }}
    symmetryMinus {{ type zeroGradient; }}
    symmetryPlus {{ type zeroGradient; }}
}}
''')


def prepare(level: str, run_root: Path, overwrite: bool) -> Path:
    case = run_root / level
    if case.exists():
        if not overwrite:
            raise FileExistsError(f"{case} exists; use --overwrite to replace it")
        shutil.rmtree(case)
    case.mkdir(parents=True)
    # The native engine userTime starts at -180 CAD, so field files must be in
    # a directory named -180 rather than OpenFOAM's conventional 0.
    shutil.copytree(ROOT / "0", case / "-180")
    for item in ("constant", "system"):
        shutil.copytree(ROOT / item, case / item)
    settings = LEVELS[level]
    (case / "system" / "blockMeshDict").write_text(
        block_mesh_dict(settings["radial"], settings["azimuthal"], settings["axial"])
    )
    return case


def execute(level: str, run_root: Path, overwrite: bool) -> dict[str, object]:
    case = prepare(level, run_root, overwrite)
    started = time.monotonic()
    row: dict[str, object] = {
        "mesh_level": level,
        "nominal_spacing_mm": LEVELS[level]["nominal_mm"],
        "radial_cells": LEVELS[level]["radial"],
        "azimuthal_cells": LEVELS[level]["azimuthal"],
        "axial_cells_bdc": LEVELS[level]["axial"],
        "processors": 1,
        "status": "failed",
        "error": "",
    }
    try:
        run(["blockMesh"], case, "log.blockMesh")
        initialise_tracer(case)
        # Standard checkMesh is the validation gate. The sector's axis-core
        # regularisation is documented in blockMeshDict generation; do not use
        # -allGeometry because its full-3D determinant heuristic is not valid
        # for the deliberately thin symmetry-sector cells.
        run(["checkMesh", "-time", "-180"], case, "log.checkMesh_bdc")
        run(["foamRun"], case, "log.foamRun")
        # Exact TDC (0 CAD) and post-motion (+180 CAD) are write times.
        run(["checkMesh", "-time", "0"], case, "log.checkMesh_tdc")
        run(["checkMesh", "-time", "180"], case, "log.checkMesh_after_motion")
        row["status"] = "ok"
    except Exception as exc:  # failures are retained in mesh-convergence output
        row["error"] = f"{type(exc).__name__}: {exc}"
    row["runtime_s"] = time.monotonic() - started
    (case / "cfd01_run_metadata.json").write_text(json.dumps(row, indent=2) + "\n")
    return row


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mesh", choices=(*LEVELS, "all"), default="all")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument(
        "--run-root", type=Path,
        default=Path(os.environ.get("CFD01_RUN_ROOT", str(Path.home() / "OpenFOAM/cfd01-cold-flow-tracer"))),
        help="WSL-local, no-space directory for transient OpenFOAM cases",
    )
    args = parser.parse_args()
    if shutil.which("foamRun") is None:
        raise SystemExit("foamRun is not on PATH; source /opt/openfoam14/etc/bashrc first.")
    chosen = list(LEVELS) if args.mesh == "all" else [args.mesh]
    run_root = args.run_root.expanduser().resolve()
    if " " in str(run_root):
        raise SystemExit("--run-root must not contain spaces (OpenFOAM requirement).")
    run_root.mkdir(parents=True, exist_ok=True)
    results = [execute(level, run_root, args.overwrite) for level in chosen]
    print(json.dumps(results, indent=2))
    if any(row["status"] != "ok" for row in results):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
